[package]
name = "tui_mods"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#i_o = { path = "../i_o" }
colored = "2.0"
crossterm = "0.23.2"
getch = "0.3.1"
chrono = "0.4"
